"""create user table

Revision ID: 0ee43f514b6b
Revises: 8ed2fa6ea2ed
Create Date: 2026-01-18 21:53:12.559223

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0ee43f514b6b"
down_revision: Union[str, Sequence[str], None] = "8ed2fa6ea2ed"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("email", sa.String(length=120), nullable=False),
        sa.Column("password", sa.String(), nullable=False),
        sa.Column("last_login", sa.DateTime(timezone=True), nullable=True),
        sa.Column("image_file", sa.String(length=200), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("username"),
    )
    op.add_column("posts", sa.Column("user_id", sa.UUID(), nullable=False))
    op.alter_column(
        "posts",
        "date_posted",
        existing_type=sa.DATE(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("CURRENT_DATE"),
    )
    op.create_index(op.f("ix_posts_user_id"), "posts", ["user_id"], unique=False)
    op.create_foreign_key(
        None, "posts", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_column("posts", "author")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "posts",
        sa.Column(
            "author", sa.VARCHAR(length=100), autoincrement=False, nullable=False
        ),
    )
    op.drop_constraint(None, "posts", type_="foreignkey")
    op.drop_index(op.f("ix_posts_user_id"), table_name="posts")
    op.alter_column(
        "posts",
        "date_posted",
        existing_type=sa.DateTime(timezone=True),
        type_=sa.DATE(),
        existing_nullable=False,
        existing_server_default=sa.text("CURRENT_DATE"),
    )
    op.drop_column("posts", "user_id")
    op.drop_table("users")
    # ### end Alembic commands ###
