"""add parent_id column to comments table

Revision ID: 50732fd89722
Revises: b99ee78e54e0
Create Date: 2026-02-16 22:11:36.494758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50732fd89722'
down_revision: Union[str, Sequence[str], None] = 'b99ee78e54e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('user_id', sa.UUID(), nullable=False))
    op.add_column('comments', sa.Column('parent_id', sa.UUID(), nullable=True))
    op.drop_index(op.f('ix_comments_author_id'), table_name='comments')
    op.create_index(op.f('ix_comments_parent_id'), 'comments', ['parent_id'], unique=False)
    op.create_index(op.f('ix_comments_user_id'), 'comments', ['user_id'], unique=False)
    op.drop_constraint(op.f('comments_author_id_fkey'), 'comments', type_='foreignkey')
    op.drop_constraint(op.f('comments_post_id_fkey'), 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'posts', ['post_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'comments', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'comments', 'comments', ['parent_id'], ['id'])
    op.drop_column('comments', 'author_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('author_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key(op.f('comments_post_id_fkey'), 'comments', 'posts', ['post_id'], ['id'])
    op.create_foreign_key(op.f('comments_author_id_fkey'), 'comments', 'users', ['author_id'], ['id'])
    op.drop_index(op.f('ix_comments_user_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_parent_id'), table_name='comments')
    op.create_index(op.f('ix_comments_author_id'), 'comments', ['author_id'], unique=False)
    op.drop_column('comments', 'parent_id')
    op.drop_column('comments', 'user_id')
    # ### end Alembic commands ###
