"""added indexes to followers table

Revision ID: f96c6e7efcb0
Revises: ec95e35725ce
Create Date: 2026-02-23 23:21:27.029904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f96c6e7efcb0'
down_revision: Union[str, Sequence[str], None] = 'ec95e35725ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_followers_follower_id', 'followers', ['follower_id'], unique=False)
    op.create_index('ix_followers_following_id', 'followers', ['following_id'], unique=False)
    op.drop_constraint(op.f('followers_follower_id_fkey'), 'followers', type_='foreignkey')
    op.drop_constraint(op.f('followers_following_id_fkey'), 'followers', type_='foreignkey')
    op.create_foreign_key(None, 'followers', 'users', ['follower_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'followers', 'users', ['following_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'followers', type_='foreignkey')
    op.drop_constraint(None, 'followers', type_='foreignkey')
    op.create_foreign_key(op.f('followers_following_id_fkey'), 'followers', 'users', ['following_id'], ['id'])
    op.create_foreign_key(op.f('followers_follower_id_fkey'), 'followers', 'users', ['follower_id'], ['id'])
    op.drop_index('ix_followers_following_id', table_name='followers')
    op.drop_index('ix_followers_follower_id', table_name='followers')
    # ### end Alembic commands ###
